# Generated by Django 5.0.2 on 2024-03-05 16:22

import core.models
import django.db.models.deletion
import django_enumfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('gender', django_enumfield.db.fields.EnumField(default=1, enum=core.models.Gender, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.CharField(max_length=128, null=True)),
                ('avatar', models.ImageField(null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
