# Generated by Django 5.0.2 on 2024-03-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birth',
            new_name='birthday',
        ),
    ]
